name: Pull Request
on:
  pull_request:
    types:
      - opened

jobs:
  # ref: https://github.com/shinGangan/.github/blob/main/.github/workflows/pull_request.yml
  set-pr:
    uses: shinGangan/.github/.github/workflows/pull_request.yml@main
    # NOTE: Renovate bot が作成した PR には実行しない
    if: ${{ contains(github.head_ref, 'renovate') == false }}
    permissions:
      contents: read
      pull-requests: write
    with:
      number: ${{ github.event.pull_request.number }}
      title: ${{ github.event.pull_request.title }}
      assignee: ${{ github.actor }}
      milestone: 'v0.3.2'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      repo: ${{ github.repository }}
