name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    # Pull requestがrenovate[bot]によるものであれば、テストをスキップする
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - name: 🤖 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm i --frozen-lockfile

      - name: 🧪 Test validation
        run: pnpm test
